# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import tariffs_pb2 as proto_dot_tariffs__pb2


class TariffsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CalculateSensorTariff = channel.unary_unary(
        '/Tariffs/CalculateSensorTariff',
        request_serializer=proto_dot_tariffs__pb2.SensorTariffsQuery.SerializeToString,
        response_deserializer=proto_dot_tariffs__pb2.TariffsCalculationsResult.FromString,
        )
    self.CalculateTariffs = channel.unary_unary(
        '/Tariffs/CalculateTariffs',
        request_serializer=proto_dot_tariffs__pb2.CalcTariffsQuery.SerializeToString,
        response_deserializer=proto_dot_tariffs__pb2.TariffsCalculationsResult.FromString,
        )
    self.FindRules = channel.unary_unary(
        '/Tariffs/FindRules',
        request_serializer=proto_dot_tariffs__pb2.SearchTariffsQuery.SerializeToString,
        response_deserializer=proto_dot_tariffs__pb2.RuleSearchResult.FromString,
        )


class TariffsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CalculateSensorTariff(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CalculateTariffs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FindRules(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TariffsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CalculateSensorTariff': grpc.unary_unary_rpc_method_handler(
          servicer.CalculateSensorTariff,
          request_deserializer=proto_dot_tariffs__pb2.SensorTariffsQuery.FromString,
          response_serializer=proto_dot_tariffs__pb2.TariffsCalculationsResult.SerializeToString,
      ),
      'CalculateTariffs': grpc.unary_unary_rpc_method_handler(
          servicer.CalculateTariffs,
          request_deserializer=proto_dot_tariffs__pb2.CalcTariffsQuery.FromString,
          response_serializer=proto_dot_tariffs__pb2.TariffsCalculationsResult.SerializeToString,
      ),
      'FindRules': grpc.unary_unary_rpc_method_handler(
          servicer.FindRules,
          request_deserializer=proto_dot_tariffs__pb2.SearchTariffsQuery.FromString,
          response_serializer=proto_dot_tariffs__pb2.RuleSearchResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Tariffs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
