# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tariffs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import utils_pb2 as proto_dot_utils__pb2
from proto import timeq_pb2 as proto_dot_timeq__pb2
from proto import companies_pb2 as proto_dot_companies__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/tariffs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13proto/tariffs.proto\x1a\x11proto/utils.proto\x1a\x11proto/timeq.proto\x1a\x15proto/companies.proto\"k\n\x12SensorTariffsQuery\x12\x18\n\x04\x66rom\x18\x01 \x01(\x0b\x32\n.TimeQuery\x12\x16\n\x02to\x18\x02 \x01(\x0b\x32\n.TimeQuery\x12\x15\n\x02id\x18\x03 \x01(\x0b\x32\t.SensorId\x12\x0c\n\x04tags\x18\x04 \x03(\t\"\xbd\x01\n\x12SearchTariffsQuery\x12\x1e\n\tsensor_id\x18\x01 \x01(\x0b\x32\t.SensorIdH\x00\x12\x18\n\x0esensor_id_none\x18\x05 \x01(\x08H\x00\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x15\n\x0bsensor_type\x18\x03 \x01(\x05H\x01\x12\x1a\n\x10sensor_type_none\x18\x04 \x01(\x08H\x01\x42\x14\n\x12optional_sensor_idB\x16\n\x14optional_sensor_type\"[\n\x10\x43\x61lcTariffsQuery\x12\x18\n\x04\x66rom\x18\x01 \x01(\x0b\x32\n.TimeQuery\x12\x16\n\x02to\x18\x02 \x01(\x0b\x32\n.TimeQuery\x12\x15\n\x02id\x18\x03 \x01(\x0b\x32\t.TariffId\"E\n\x1bTariffMonoCalculationResult\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x17\n\x0f\x64imensions_name\x18\x02 \x01(\t\"\x9e\x01\n\x17TariffCalculationResult\x12\x1b\n\x06tariff\x18\x01 \x01(\x0b\x32\x0b.TariffInfo\x12\x46\n\x1etariff_mono_calculation_result\x18\x02 \x01(\x0b\x32\x1c.TariffMonoCalculationResultH\x00\x12\x15\n\x04null\x18\x03 \x01(\x0b\x32\x05.VoidH\x00\x42\x07\n\x05value\"R\n\x19TariffsCalculationsResult\x12\x35\n\x13\x63\x61lculation_results\x18\x01 \x03(\x0b\x32\x18.TariffCalculationResult\"O\n\x04Rule\x12\x1c\n\tsensro_id\x18\x01 \x01(\x0b\x32\t.SensorId\x12\x1b\n\x06tariff\x18\x02 \x01(\x0b\x32\x0b.TariffInfo\x12\x0c\n\x04tags\x18\x03 \x03(\t\"(\n\x10RuleSearchResult\x12\x14\n\x05rules\x18\x01 \x03(\x0b\x32\x05.Rule2\xd1\x01\n\x07Tariffs\x12J\n\x15\x43\x61lculateSensorTariff\x12\x13.SensorTariffsQuery\x1a\x1a.TariffsCalculationsResult\"\x00\x12\x43\n\x10\x43\x61lculateTariffs\x12\x11.CalcTariffsQuery\x1a\x1a.TariffsCalculationsResult\"\x00\x12\x35\n\tFindRules\x12\x13.SearchTariffsQuery\x1a\x11.RuleSearchResult\"\x00\x62\x06proto3')
  ,
  dependencies=[proto_dot_utils__pb2.DESCRIPTOR,proto_dot_timeq__pb2.DESCRIPTOR,proto_dot_companies__pb2.DESCRIPTOR,])




_SENSORTARIFFSQUERY = _descriptor.Descriptor(
  name='SensorTariffsQuery',
  full_name='SensorTariffsQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='SensorTariffsQuery.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='SensorTariffsQuery.to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='SensorTariffsQuery.id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='SensorTariffsQuery.tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=191,
)


_SEARCHTARIFFSQUERY = _descriptor.Descriptor(
  name='SearchTariffsQuery',
  full_name='SearchTariffsQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='SearchTariffsQuery.sensor_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id_none', full_name='SearchTariffsQuery.sensor_id_none', index=1,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='SearchTariffsQuery.tags', index=2,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='SearchTariffsQuery.sensor_type', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_type_none', full_name='SearchTariffsQuery.sensor_type_none', index=4,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_sensor_id', full_name='SearchTariffsQuery.optional_sensor_id',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='optional_sensor_type', full_name='SearchTariffsQuery.optional_sensor_type',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=194,
  serialized_end=383,
)


_CALCTARIFFSQUERY = _descriptor.Descriptor(
  name='CalcTariffsQuery',
  full_name='CalcTariffsQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='CalcTariffsQuery.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='CalcTariffsQuery.to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='CalcTariffsQuery.id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=476,
)


_TARIFFMONOCALCULATIONRESULT = _descriptor.Descriptor(
  name='TariffMonoCalculationResult',
  full_name='TariffMonoCalculationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TariffMonoCalculationResult.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dimensions_name', full_name='TariffMonoCalculationResult.dimensions_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=547,
)


_TARIFFCALCULATIONRESULT = _descriptor.Descriptor(
  name='TariffCalculationResult',
  full_name='TariffCalculationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tariff', full_name='TariffCalculationResult.tariff', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tariff_mono_calculation_result', full_name='TariffCalculationResult.tariff_mono_calculation_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='null', full_name='TariffCalculationResult.null', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='TariffCalculationResult.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=550,
  serialized_end=708,
)


_TARIFFSCALCULATIONSRESULT = _descriptor.Descriptor(
  name='TariffsCalculationsResult',
  full_name='TariffsCalculationsResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='calculation_results', full_name='TariffsCalculationsResult.calculation_results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=710,
  serialized_end=792,
)


_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensro_id', full_name='Rule.sensro_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tariff', full_name='Rule.tariff', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='Rule.tags', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=794,
  serialized_end=873,
)


_RULESEARCHRESULT = _descriptor.Descriptor(
  name='RuleSearchResult',
  full_name='RuleSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='RuleSearchResult.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=875,
  serialized_end=915,
)

_SENSORTARIFFSQUERY.fields_by_name['from'].message_type = proto_dot_timeq__pb2._TIMEQUERY
_SENSORTARIFFSQUERY.fields_by_name['to'].message_type = proto_dot_timeq__pb2._TIMEQUERY
_SENSORTARIFFSQUERY.fields_by_name['id'].message_type = proto_dot_utils__pb2._SENSORID
_SEARCHTARIFFSQUERY.fields_by_name['sensor_id'].message_type = proto_dot_utils__pb2._SENSORID
_SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_id'].fields.append(
  _SEARCHTARIFFSQUERY.fields_by_name['sensor_id'])
_SEARCHTARIFFSQUERY.fields_by_name['sensor_id'].containing_oneof = _SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_id']
_SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_id'].fields.append(
  _SEARCHTARIFFSQUERY.fields_by_name['sensor_id_none'])
_SEARCHTARIFFSQUERY.fields_by_name['sensor_id_none'].containing_oneof = _SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_id']
_SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_type'].fields.append(
  _SEARCHTARIFFSQUERY.fields_by_name['sensor_type'])
_SEARCHTARIFFSQUERY.fields_by_name['sensor_type'].containing_oneof = _SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_type']
_SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_type'].fields.append(
  _SEARCHTARIFFSQUERY.fields_by_name['sensor_type_none'])
_SEARCHTARIFFSQUERY.fields_by_name['sensor_type_none'].containing_oneof = _SEARCHTARIFFSQUERY.oneofs_by_name['optional_sensor_type']
_CALCTARIFFSQUERY.fields_by_name['from'].message_type = proto_dot_timeq__pb2._TIMEQUERY
_CALCTARIFFSQUERY.fields_by_name['to'].message_type = proto_dot_timeq__pb2._TIMEQUERY
_CALCTARIFFSQUERY.fields_by_name['id'].message_type = proto_dot_utils__pb2._TARIFFID
_TARIFFCALCULATIONRESULT.fields_by_name['tariff'].message_type = proto_dot_companies__pb2._TARIFFINFO
_TARIFFCALCULATIONRESULT.fields_by_name['tariff_mono_calculation_result'].message_type = _TARIFFMONOCALCULATIONRESULT
_TARIFFCALCULATIONRESULT.fields_by_name['null'].message_type = proto_dot_utils__pb2._VOID
_TARIFFCALCULATIONRESULT.oneofs_by_name['value'].fields.append(
  _TARIFFCALCULATIONRESULT.fields_by_name['tariff_mono_calculation_result'])
_TARIFFCALCULATIONRESULT.fields_by_name['tariff_mono_calculation_result'].containing_oneof = _TARIFFCALCULATIONRESULT.oneofs_by_name['value']
_TARIFFCALCULATIONRESULT.oneofs_by_name['value'].fields.append(
  _TARIFFCALCULATIONRESULT.fields_by_name['null'])
_TARIFFCALCULATIONRESULT.fields_by_name['null'].containing_oneof = _TARIFFCALCULATIONRESULT.oneofs_by_name['value']
_TARIFFSCALCULATIONSRESULT.fields_by_name['calculation_results'].message_type = _TARIFFCALCULATIONRESULT
_RULE.fields_by_name['sensro_id'].message_type = proto_dot_utils__pb2._SENSORID
_RULE.fields_by_name['tariff'].message_type = proto_dot_companies__pb2._TARIFFINFO
_RULESEARCHRESULT.fields_by_name['rules'].message_type = _RULE
DESCRIPTOR.message_types_by_name['SensorTariffsQuery'] = _SENSORTARIFFSQUERY
DESCRIPTOR.message_types_by_name['SearchTariffsQuery'] = _SEARCHTARIFFSQUERY
DESCRIPTOR.message_types_by_name['CalcTariffsQuery'] = _CALCTARIFFSQUERY
DESCRIPTOR.message_types_by_name['TariffMonoCalculationResult'] = _TARIFFMONOCALCULATIONRESULT
DESCRIPTOR.message_types_by_name['TariffCalculationResult'] = _TARIFFCALCULATIONRESULT
DESCRIPTOR.message_types_by_name['TariffsCalculationsResult'] = _TARIFFSCALCULATIONSRESULT
DESCRIPTOR.message_types_by_name['Rule'] = _RULE
DESCRIPTOR.message_types_by_name['RuleSearchResult'] = _RULESEARCHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorTariffsQuery = _reflection.GeneratedProtocolMessageType('SensorTariffsQuery', (_message.Message,), dict(
  DESCRIPTOR = _SENSORTARIFFSQUERY,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:SensorTariffsQuery)
  ))
_sym_db.RegisterMessage(SensorTariffsQuery)

SearchTariffsQuery = _reflection.GeneratedProtocolMessageType('SearchTariffsQuery', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHTARIFFSQUERY,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:SearchTariffsQuery)
  ))
_sym_db.RegisterMessage(SearchTariffsQuery)

CalcTariffsQuery = _reflection.GeneratedProtocolMessageType('CalcTariffsQuery', (_message.Message,), dict(
  DESCRIPTOR = _CALCTARIFFSQUERY,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:CalcTariffsQuery)
  ))
_sym_db.RegisterMessage(CalcTariffsQuery)

TariffMonoCalculationResult = _reflection.GeneratedProtocolMessageType('TariffMonoCalculationResult', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFMONOCALCULATIONRESULT,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:TariffMonoCalculationResult)
  ))
_sym_db.RegisterMessage(TariffMonoCalculationResult)

TariffCalculationResult = _reflection.GeneratedProtocolMessageType('TariffCalculationResult', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFCALCULATIONRESULT,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:TariffCalculationResult)
  ))
_sym_db.RegisterMessage(TariffCalculationResult)

TariffsCalculationsResult = _reflection.GeneratedProtocolMessageType('TariffsCalculationsResult', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFSCALCULATIONSRESULT,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:TariffsCalculationsResult)
  ))
_sym_db.RegisterMessage(TariffsCalculationsResult)

Rule = _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), dict(
  DESCRIPTOR = _RULE,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:Rule)
  ))
_sym_db.RegisterMessage(Rule)

RuleSearchResult = _reflection.GeneratedProtocolMessageType('RuleSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _RULESEARCHRESULT,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:RuleSearchResult)
  ))
_sym_db.RegisterMessage(RuleSearchResult)



_TARIFFS = _descriptor.ServiceDescriptor(
  name='Tariffs',
  full_name='Tariffs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=918,
  serialized_end=1127,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalculateSensorTariff',
    full_name='Tariffs.CalculateSensorTariff',
    index=0,
    containing_service=None,
    input_type=_SENSORTARIFFSQUERY,
    output_type=_TARIFFSCALCULATIONSRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CalculateTariffs',
    full_name='Tariffs.CalculateTariffs',
    index=1,
    containing_service=None,
    input_type=_CALCTARIFFSQUERY,
    output_type=_TARIFFSCALCULATIONSRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FindRules',
    full_name='Tariffs.FindRules',
    index=2,
    containing_service=None,
    input_type=_SEARCHTARIFFSQUERY,
    output_type=_RULESEARCHRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TARIFFS)

DESCRIPTOR.services_by_name['Tariffs'] = _TARIFFS

# @@protoc_insertion_point(module_scope)
