# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/objects.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import utils_pb2 as proto_dot_utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/objects.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13proto/objects.proto\x1a\x11proto/utils.proto\"\x90\x01\n\nSensorInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x63tivation_date\x18\x03 \x01(\x04\x12\x0e\n\x06status\x18\x04 \x01(\x04\x12\x19\n\x11\x64\x65\x61\x63tivation_date\x18\x05 \x01(\x04\x12\x13\n\x0bsensor_type\x18\x06 \x01(\x04\x12\x0f\n\x07\x63ompany\x18\x07 \x01(\t\"\xc1\x01\n\x0e\x43ontrollerInfo\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04meta\x18\x03 \x01(\t\x12\x17\n\x0f\x61\x63tivation_date\x18\x04 \x01(\x04\x12\x0e\n\x06status\x18\x05 \x01(\x04\x12\x0b\n\x03mac\x18\x06 \x01(\t\x12\x19\n\x11\x64\x65\x61\x63tivation_date\x18\x07 \x01(\x04\x12\x17\n\x0f\x63ontroller_type\x18\x08 \x01(\x04\x12\x1c\n\x07sensors\x18\t \x03(\x0b\x32\x0b.SensorInfo\"\\\n\nObjectInfo\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x61\x64res\x18\x03 \x01(\t\x12$\n\x0b\x63ontrollers\x18\x04 \x03(\x0b\x32\x0f.ControllerInfo\"6\n\tUserInfoH\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x1c\n\x07objects\x18\x02 \x03(\x0b\x32\x0b.ObjectInfo2\x98\x01\n\rObjectService\x12%\n\x0cGetUsersInfo\x12\x07.UserId\x1a\n.UserInfoH\"\x00\x12\x35\n\x11GetControllerInfo\x12\r.ControllerId\x1a\x0f.ControllerInfo\"\x00\x12)\n\rGetSensorInfo\x12\t.SensorId\x1a\x0b.SensorInfo\"\x00\x62\x06proto3')
  ,
  dependencies=[proto_dot_utils__pb2.DESCRIPTOR,])




_SENSORINFO = _descriptor.Descriptor(
  name='SensorInfo',
  full_name='SensorInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SensorInfo.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='SensorInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_date', full_name='SensorInfo.activation_date', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='SensorInfo.status', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deactivation_date', full_name='SensorInfo.deactivation_date', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='SensorInfo.sensor_type', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='SensorInfo.company', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=187,
)


_CONTROLLERINFO = _descriptor.Descriptor(
  name='ControllerInfo',
  full_name='ControllerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ControllerInfo.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ControllerInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='ControllerInfo.meta', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_date', full_name='ControllerInfo.activation_date', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ControllerInfo.status', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mac', full_name='ControllerInfo.mac', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deactivation_date', full_name='ControllerInfo.deactivation_date', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controller_type', full_name='ControllerInfo.controller_type', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='ControllerInfo.sensors', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=383,
)


_OBJECTINFO = _descriptor.Descriptor(
  name='ObjectInfo',
  full_name='ObjectInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ObjectInfo.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ObjectInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ObjectInfo.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='controllers', full_name='ObjectInfo.controllers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=477,
)


_USERINFOH = _descriptor.Descriptor(
  name='UserInfoH',
  full_name='UserInfoH',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='UserInfoH.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='UserInfoH.objects', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=533,
)

_CONTROLLERINFO.fields_by_name['sensors'].message_type = _SENSORINFO
_OBJECTINFO.fields_by_name['controllers'].message_type = _CONTROLLERINFO
_USERINFOH.fields_by_name['objects'].message_type = _OBJECTINFO
DESCRIPTOR.message_types_by_name['SensorInfo'] = _SENSORINFO
DESCRIPTOR.message_types_by_name['ControllerInfo'] = _CONTROLLERINFO
DESCRIPTOR.message_types_by_name['ObjectInfo'] = _OBJECTINFO
DESCRIPTOR.message_types_by_name['UserInfoH'] = _USERINFOH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorInfo = _reflection.GeneratedProtocolMessageType('SensorInfo', (_message.Message,), dict(
  DESCRIPTOR = _SENSORINFO,
  __module__ = 'proto.objects_pb2'
  # @@protoc_insertion_point(class_scope:SensorInfo)
  ))
_sym_db.RegisterMessage(SensorInfo)

ControllerInfo = _reflection.GeneratedProtocolMessageType('ControllerInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERINFO,
  __module__ = 'proto.objects_pb2'
  # @@protoc_insertion_point(class_scope:ControllerInfo)
  ))
_sym_db.RegisterMessage(ControllerInfo)

ObjectInfo = _reflection.GeneratedProtocolMessageType('ObjectInfo', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTINFO,
  __module__ = 'proto.objects_pb2'
  # @@protoc_insertion_point(class_scope:ObjectInfo)
  ))
_sym_db.RegisterMessage(ObjectInfo)

UserInfoH = _reflection.GeneratedProtocolMessageType('UserInfoH', (_message.Message,), dict(
  DESCRIPTOR = _USERINFOH,
  __module__ = 'proto.objects_pb2'
  # @@protoc_insertion_point(class_scope:UserInfoH)
  ))
_sym_db.RegisterMessage(UserInfoH)



_OBJECTSERVICE = _descriptor.ServiceDescriptor(
  name='ObjectService',
  full_name='ObjectService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=536,
  serialized_end=688,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUsersInfo',
    full_name='ObjectService.GetUsersInfo',
    index=0,
    containing_service=None,
    input_type=proto_dot_utils__pb2._USERID,
    output_type=_USERINFOH,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetControllerInfo',
    full_name='ObjectService.GetControllerInfo',
    index=1,
    containing_service=None,
    input_type=proto_dot_utils__pb2._CONTROLLERID,
    output_type=_CONTROLLERINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetSensorInfo',
    full_name='ObjectService.GetSensorInfo',
    index=2,
    containing_service=None,
    input_type=proto_dot_utils__pb2._SENSORID,
    output_type=_SENSORINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTSERVICE)

DESCRIPTOR.services_by_name['ObjectService'] = _OBJECTSERVICE

# @@protoc_insertion_point(module_scope)
