# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import objects_pb2 as proto_dot_objects__pb2
from proto import utils_pb2 as proto_dot_utils__pb2


class ObjectServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUsersInfo = channel.unary_unary(
        '/ObjectService/GetUsersInfo',
        request_serializer=proto_dot_utils__pb2.UserId.SerializeToString,
        response_deserializer=proto_dot_objects__pb2.UserInfoH.FromString,
        )
    self.GetControllerInfo = channel.unary_unary(
        '/ObjectService/GetControllerInfo',
        request_serializer=proto_dot_utils__pb2.ControllerId.SerializeToString,
        response_deserializer=proto_dot_objects__pb2.ControllerInfo.FromString,
        )
    self.GetSensorInfo = channel.unary_unary(
        '/ObjectService/GetSensorInfo',
        request_serializer=proto_dot_utils__pb2.SensorId.SerializeToString,
        response_deserializer=proto_dot_objects__pb2.SensorInfo.FromString,
        )


class ObjectServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUsersInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetControllerInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSensorInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUsersInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUsersInfo,
          request_deserializer=proto_dot_utils__pb2.UserId.FromString,
          response_serializer=proto_dot_objects__pb2.UserInfoH.SerializeToString,
      ),
      'GetControllerInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetControllerInfo,
          request_deserializer=proto_dot_utils__pb2.ControllerId.FromString,
          response_serializer=proto_dot_objects__pb2.ControllerInfo.SerializeToString,
      ),
      'GetSensorInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetSensorInfo,
          request_deserializer=proto_dot_utils__pb2.SensorId.FromString,
          response_serializer=proto_dot_objects__pb2.SensorInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ObjectService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
