# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stats.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bstats.proto\"W\n\nSensorStat\x12\x15\n\rcurrent_month\x18\x01 \x01(\x01\x12\x17\n\x0fprev_year_month\x18\x02 \x01(\x01\x12\x19\n\x11prev_year_average\x18\x03 \x01(\x01\"\x1d\n\x08SensorId\x12\x11\n\tsensor_id\x18\x01 \x01(\x04\x32\x39\n\x0cStatsService\x12)\n\rGetSensorStat\x12\t.SensorId\x1a\x0b.SensorStat\"\x00\x62\x06proto3')
)




_SENSORSTAT = _descriptor.Descriptor(
  name='SensorStat',
  full_name='SensorStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_month', full_name='SensorStat.current_month', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_year_month', full_name='SensorStat.prev_year_month', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_year_average', full_name='SensorStat.prev_year_average', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=102,
)


_SENSORID = _descriptor.Descriptor(
  name='SensorId',
  full_name='SensorId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='SensorId.sensor_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['SensorStat'] = _SENSORSTAT
DESCRIPTOR.message_types_by_name['SensorId'] = _SENSORID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorStat = _reflection.GeneratedProtocolMessageType('SensorStat', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSTAT,
  __module__ = 'stats_pb2'
  # @@protoc_insertion_point(class_scope:SensorStat)
  ))
_sym_db.RegisterMessage(SensorStat)

SensorId = _reflection.GeneratedProtocolMessageType('SensorId', (_message.Message,), dict(
  DESCRIPTOR = _SENSORID,
  __module__ = 'stats_pb2'
  # @@protoc_insertion_point(class_scope:SensorId)
  ))
_sym_db.RegisterMessage(SensorId)



_STATSSERVICE = _descriptor.ServiceDescriptor(
  name='StatsService',
  full_name='StatsService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=135,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSensorStat',
    full_name='StatsService.GetSensorStat',
    index=0,
    containing_service=None,
    input_type=_SENSORID,
    output_type=_SENSORSTAT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STATSSERVICE)

DESCRIPTOR.services_by_name['StatsService'] = _STATSSERVICE

# @@protoc_insertion_point(module_scope)
