# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/companies.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import utils_pb2 as proto_dot_utils__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/companies.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15proto/companies.proto\x1a\x11proto/utils.proto\"l\n\x0b\x43ompanyInfo\x12\x16\n\x02id\x18\x01 \x01(\x0b\x32\n.CompanyId\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x17\n\x0f\x62\x61nk_account_id\x18\x05 \x01(\t\"N\n\x13\x43ompanyExtendedInfo\x12\x19\n\x03inf\x18\x01 \x01(\x0b\x32\x0c.CompanyInfo\x12\x1c\n\x07tariffs\x18\x02 \x03(\x0b\x32\x0b.TariffInfo\"&\n\x15TariffCalculationMono\x12\r\n\x05value\x18\x01 \x01(\x01\"7\n\x19TariffCalculationDayNight\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\x01\x12\r\n\x05night\x18\x02 \x01(\x01\"\xb1\x01\n\nTariffInfo\x12\x15\n\x02id\x18\x01 \x01(\x0b\x32\t.TariffId\x12\x1b\n\x07\x63ompany\x18\x02 \x01(\x0b\x32\n.CompanyId\x12\x0c\n\x04name\x18\x03 \x01(\t\x12&\n\x04mono\x18\x04 \x01(\x0b\x32\x16.TariffCalculationMonoH\x00\x12/\n\tday_night\x18\x05 \x01(\x0b\x32\x1a.TariffCalculationDayNightH\x00\x42\x08\n\x06tariff2\xa0\x01\n\x07\x43ompany\x12,\n\x0eGetCompanyInfo\x12\n.CompanyId\x1a\x0c.CompanyInfo\"\x00\x12)\n\rGetTariffInfo\x12\t.TariffId\x1a\x0b.TariffInfo\"\x00\x12<\n\x16GetCompanyExtendedInfo\x12\n.CompanyId\x1a\x14.CompanyExtendedInfo\"\x00\x62\x06proto3')
  ,
  dependencies=[proto_dot_utils__pb2.DESCRIPTOR,])




_COMPANYINFO = _descriptor.Descriptor(
  name='CompanyInfo',
  full_name='CompanyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CompanyInfo.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='CompanyInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='CompanyInfo.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone', full_name='CompanyInfo.phone', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bank_account_id', full_name='CompanyInfo.bank_account_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=152,
)


_COMPANYEXTENDEDINFO = _descriptor.Descriptor(
  name='CompanyExtendedInfo',
  full_name='CompanyExtendedInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inf', full_name='CompanyExtendedInfo.inf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tariffs', full_name='CompanyExtendedInfo.tariffs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=232,
)


_TARIFFCALCULATIONMONO = _descriptor.Descriptor(
  name='TariffCalculationMono',
  full_name='TariffCalculationMono',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='TariffCalculationMono.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=272,
)


_TARIFFCALCULATIONDAYNIGHT = _descriptor.Descriptor(
  name='TariffCalculationDayNight',
  full_name='TariffCalculationDayNight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='TariffCalculationDayNight.day', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='night', full_name='TariffCalculationDayNight.night', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=329,
)


_TARIFFINFO = _descriptor.Descriptor(
  name='TariffInfo',
  full_name='TariffInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TariffInfo.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='TariffInfo.company', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='TariffInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mono', full_name='TariffInfo.mono', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day_night', full_name='TariffInfo.day_night', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='tariff', full_name='TariffInfo.tariff',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=332,
  serialized_end=509,
)

_COMPANYINFO.fields_by_name['id'].message_type = proto_dot_utils__pb2._COMPANYID
_COMPANYEXTENDEDINFO.fields_by_name['inf'].message_type = _COMPANYINFO
_COMPANYEXTENDEDINFO.fields_by_name['tariffs'].message_type = _TARIFFINFO
_TARIFFINFO.fields_by_name['id'].message_type = proto_dot_utils__pb2._TARIFFID
_TARIFFINFO.fields_by_name['company'].message_type = proto_dot_utils__pb2._COMPANYID
_TARIFFINFO.fields_by_name['mono'].message_type = _TARIFFCALCULATIONMONO
_TARIFFINFO.fields_by_name['day_night'].message_type = _TARIFFCALCULATIONDAYNIGHT
_TARIFFINFO.oneofs_by_name['tariff'].fields.append(
  _TARIFFINFO.fields_by_name['mono'])
_TARIFFINFO.fields_by_name['mono'].containing_oneof = _TARIFFINFO.oneofs_by_name['tariff']
_TARIFFINFO.oneofs_by_name['tariff'].fields.append(
  _TARIFFINFO.fields_by_name['day_night'])
_TARIFFINFO.fields_by_name['day_night'].containing_oneof = _TARIFFINFO.oneofs_by_name['tariff']
DESCRIPTOR.message_types_by_name['CompanyInfo'] = _COMPANYINFO
DESCRIPTOR.message_types_by_name['CompanyExtendedInfo'] = _COMPANYEXTENDEDINFO
DESCRIPTOR.message_types_by_name['TariffCalculationMono'] = _TARIFFCALCULATIONMONO
DESCRIPTOR.message_types_by_name['TariffCalculationDayNight'] = _TARIFFCALCULATIONDAYNIGHT
DESCRIPTOR.message_types_by_name['TariffInfo'] = _TARIFFINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompanyInfo = _reflection.GeneratedProtocolMessageType('CompanyInfo', (_message.Message,), dict(
  DESCRIPTOR = _COMPANYINFO,
  __module__ = 'proto.companies_pb2'
  # @@protoc_insertion_point(class_scope:CompanyInfo)
  ))
_sym_db.RegisterMessage(CompanyInfo)

CompanyExtendedInfo = _reflection.GeneratedProtocolMessageType('CompanyExtendedInfo', (_message.Message,), dict(
  DESCRIPTOR = _COMPANYEXTENDEDINFO,
  __module__ = 'proto.companies_pb2'
  # @@protoc_insertion_point(class_scope:CompanyExtendedInfo)
  ))
_sym_db.RegisterMessage(CompanyExtendedInfo)

TariffCalculationMono = _reflection.GeneratedProtocolMessageType('TariffCalculationMono', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFCALCULATIONMONO,
  __module__ = 'proto.companies_pb2'
  # @@protoc_insertion_point(class_scope:TariffCalculationMono)
  ))
_sym_db.RegisterMessage(TariffCalculationMono)

TariffCalculationDayNight = _reflection.GeneratedProtocolMessageType('TariffCalculationDayNight', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFCALCULATIONDAYNIGHT,
  __module__ = 'proto.companies_pb2'
  # @@protoc_insertion_point(class_scope:TariffCalculationDayNight)
  ))
_sym_db.RegisterMessage(TariffCalculationDayNight)

TariffInfo = _reflection.GeneratedProtocolMessageType('TariffInfo', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFINFO,
  __module__ = 'proto.companies_pb2'
  # @@protoc_insertion_point(class_scope:TariffInfo)
  ))
_sym_db.RegisterMessage(TariffInfo)



_COMPANY = _descriptor.ServiceDescriptor(
  name='Company',
  full_name='Company',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=512,
  serialized_end=672,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCompanyInfo',
    full_name='Company.GetCompanyInfo',
    index=0,
    containing_service=None,
    input_type=proto_dot_utils__pb2._COMPANYID,
    output_type=_COMPANYINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTariffInfo',
    full_name='Company.GetTariffInfo',
    index=1,
    containing_service=None,
    input_type=proto_dot_utils__pb2._TARIFFID,
    output_type=_TARIFFINFO,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCompanyExtendedInfo',
    full_name='Company.GetCompanyExtendedInfo',
    index=2,
    containing_service=None,
    input_type=proto_dot_utils__pb2._COMPANYID,
    output_type=_COMPANYEXTENDEDINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPANY)

DESCRIPTOR.services_by_name['Company'] = _COMPANY

# @@protoc_insertion_point(module_scope)
