# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tariffs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import utils_pb2 as proto_dot_utils__pb2
from proto import timeq_pb2 as proto_dot_timeq__pb2
from proto import companies_pb2 as proto_dot_companies__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/tariffs.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13proto/tariffs.proto\x1a\x11proto/utils.proto\x1a\x11proto/timeq.proto\x1a\x15proto/companies.proto\"V\n\x0bTariffQuery\x12\x18\n\x04\x66rom\x18\x01 \x01(\x0b\x32\n.TimeQuery\x12\x16\n\x02to\x18\x02 \x01(\x0b\x32\n.TimeQuery\x12\x15\n\x02id\x18\x03 \x01(\x0b\x32\t.SensorId\"E\n\x17TariffCalculationResult\x12\x1b\n\x06tariff\x18\x01 \x01(\x0b\x32\x0b.TariffInfo\x12\r\n\x05value\x18\x02 \x01(\x01\x32H\n\x07Tariffs\x12=\n\x11\x43\x61lculatePayments\x12\x0c.TariffQuery\x1a\x18.TariffCalculationResult\"\x00\x62\x06proto3')
  ,
  dependencies=[proto_dot_utils__pb2.DESCRIPTOR,proto_dot_timeq__pb2.DESCRIPTOR,proto_dot_companies__pb2.DESCRIPTOR,])




_TARIFFQUERY = _descriptor.Descriptor(
  name='TariffQuery',
  full_name='TariffQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='TariffQuery.from', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='TariffQuery.to', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='TariffQuery.id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=170,
)


_TARIFFCALCULATIONRESULT = _descriptor.Descriptor(
  name='TariffCalculationResult',
  full_name='TariffCalculationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tariff', full_name='TariffCalculationResult.tariff', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='TariffCalculationResult.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=241,
)

_TARIFFQUERY.fields_by_name['from'].message_type = proto_dot_timeq__pb2._TIMEQUERY
_TARIFFQUERY.fields_by_name['to'].message_type = proto_dot_timeq__pb2._TIMEQUERY
_TARIFFQUERY.fields_by_name['id'].message_type = proto_dot_utils__pb2._SENSORID
_TARIFFCALCULATIONRESULT.fields_by_name['tariff'].message_type = proto_dot_companies__pb2._TARIFFINFO
DESCRIPTOR.message_types_by_name['TariffQuery'] = _TARIFFQUERY
DESCRIPTOR.message_types_by_name['TariffCalculationResult'] = _TARIFFCALCULATIONRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TariffQuery = _reflection.GeneratedProtocolMessageType('TariffQuery', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFQUERY,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:TariffQuery)
  ))
_sym_db.RegisterMessage(TariffQuery)

TariffCalculationResult = _reflection.GeneratedProtocolMessageType('TariffCalculationResult', (_message.Message,), dict(
  DESCRIPTOR = _TARIFFCALCULATIONRESULT,
  __module__ = 'proto.tariffs_pb2'
  # @@protoc_insertion_point(class_scope:TariffCalculationResult)
  ))
_sym_db.RegisterMessage(TariffCalculationResult)



_TARIFFS = _descriptor.ServiceDescriptor(
  name='Tariffs',
  full_name='Tariffs',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=243,
  serialized_end=315,
  methods=[
  _descriptor.MethodDescriptor(
    name='CalculatePayments',
    full_name='Tariffs.CalculatePayments',
    index=0,
    containing_service=None,
    input_type=_TARIFFQUERY,
    output_type=_TARIFFCALCULATIONRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TARIFFS)

DESCRIPTOR.services_by_name['Tariffs'] = _TARIFFS

# @@protoc_insertion_point(module_scope)
