FROM python:3

WORKDIR /application

ADD requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

ADD auth auth
ADD Makefile Makefile

ADD etc etc

EXPOSE 5000

ENTRYPOINT [ "make" ]
CMD [ "start_4_docker" ]
