# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stats_pb2 as stats__pb2


class StatsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSensorStat = channel.unary_unary(
        '/StatsService/GetSensorStat',
        request_serializer=stats__pb2.SensorId.SerializeToString,
        response_deserializer=stats__pb2.SensorStat.FromString,
        )


class StatsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSensorStat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSensorStat': grpc.unary_unary_rpc_method_handler(
          servicer.GetSensorStat,
          request_deserializer=stats__pb2.SensorId.FromString,
          response_serializer=stats__pb2.SensorStat.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'StatsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
