# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/utils.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11proto/utils.proto\"\x1d\n\x08SensorId\x12\x11\n\tsensor_id\x18\x01 \x01(\x04\x62\x06proto3')
)




_SENSORID = _descriptor.Descriptor(
  name='SensorId',
  full_name='SensorId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='SensorId.sensor_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['SensorId'] = _SENSORID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorId = _reflection.GeneratedProtocolMessageType('SensorId', (_message.Message,), dict(
  DESCRIPTOR = _SENSORID,
  __module__ = 'proto.utils_pb2'
  # @@protoc_insertion_point(class_scope:SensorId)
  ))
_sym_db.RegisterMessage(SensorId)


# @@protoc_insertion_point(module_scope)
