# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import users_pb2 as proto_dot_users__pb2
from proto import utils_pb2 as proto_dot_utils__pb2


class UserInfoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserInfo = channel.unary_unary(
        '/UserInfoService/GetUserInfo',
        request_serializer=proto_dot_utils__pb2.UserId.SerializeToString,
        response_deserializer=proto_dot_users__pb2.UserInfo.FromString,
        )


class UserInfoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUserInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserInfoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfo,
          request_deserializer=proto_dot_utils__pb2.UserId.FromString,
          response_serializer=proto_dot_users__pb2.UserInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'UserInfoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
