# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import tariffs_pb2 as proto_dot_tariffs__pb2


class TariffsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CalculatePayments = channel.unary_unary(
        '/Tariffs/CalculatePayments',
        request_serializer=proto_dot_tariffs__pb2.TariffQuery.SerializeToString,
        response_deserializer=proto_dot_tariffs__pb2.TariffCalculationResult.FromString,
        )


class TariffsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CalculatePayments(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TariffsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CalculatePayments': grpc.unary_unary_rpc_method_handler(
          servicer.CalculatePayments,
          request_deserializer=proto_dot_tariffs__pb2.TariffQuery.FromString,
          response_serializer=proto_dot_tariffs__pb2.TariffCalculationResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Tariffs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
