# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import data_pb2 as proto_dot_data__pb2


class DataServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSensorData = channel.unary_stream(
        '/DataService/GetSensorData',
        request_serializer=proto_dot_data__pb2.MeterQuery.SerializeToString,
        response_deserializer=proto_dot_data__pb2.MeterData.FromString,
        )


class DataServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSensorData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSensorData': grpc.unary_stream_rpc_method_handler(
          servicer.GetSensorData,
          request_deserializer=proto_dot_data__pb2.MeterQuery.FromString,
          response_serializer=proto_dot_data__pb2.MeterData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
